export const PLANNER_DATA = [
   {
      month: "January 2026",
      days: [
         { dt: 1, day: "Thu", event: "New Year's Day - Holiday", do: "-" },
         { dt: 2, day: "Fri", event: "", do: "-" },
         { dt: 3, day: "Sat", event: "", do: "-" },
         { dt: 4, day: "Sun", event: "", do: "-" },
         { dt: 5, day: "Mon", event: "Enrolment Day", do: "-" },
         { dt: 6, day: "Tue", event: "", do: "-" },
         { dt: 7, day: "Wed", event: "", do: "-" },
         { dt: 8, day: "Thu", event: "Commencement of Classes", do: "1" },
         { dt: 9, day: "Fri", event: "", do: "2" },
         { dt: 10, day: "Sat", event: "", do: "-" },
         { dt: 11, day: "Sun", event: "", do: "-" },
         { dt: 12, day: "Mon", event: "", do: "3" },
         { dt: 13, day: "Tue", event: "", do: "4" },
         { dt: 14, day: "Wed", event: "", do: "5" },
         { dt: 15, day: "Thu", event: "Pongal - Holiday", do: "-" },
         { dt: 16, day: "Fri", event: "Thiruvalluvar Day - Holiday", do: "-" },
         { dt: 17, day: "Sat", event: "Uzhavar Thirunal - Holiday", do: "-" },
         { dt: 18, day: "Sun", event: "", do: "-" },
         { dt: 19, day: "Mon", event: "", do: "1" },
         { dt: 20, day: "Tue", event: "", do: "2" },
         { dt: 21, day: "Wed", event: "", do: "3" },
         { dt: 22, day: "Thu", event: "", do: "4" },
         { dt: 23, day: "Fri", event: "", do: "5" },
         { dt: 24, day: "Sat", event: "", do: "-" },
         { dt: 25, day: "Sun", event: "", do: "-" },
         { dt: 26, day: "Mon", event: "Republic Day - Holiday", do: "-" },
         { dt: 27, day: "Tue", event: "", do: "1" },
         { dt: 28, day: "Wed", event: "", do: "2" },
         { dt: 29, day: "Thu", event: "", do: "3" },
         { dt: 30, day: "Fri", event: "", do: "4" },
         { dt: 31, day: "Sat", event: "", do: "-" },
      ]
   },
   {
      month: "February 2026",
      days: [
         { dt: 1, day: "Sun", event: "Thaipoosam - Holiday", do: "-" },
         { dt: 2, day: "Mon", event: "", do: "5" },
         { dt: 3, day: "Tue", event: "", do: "1" },
         { dt: 4, day: "Wed", event: "Holi", do: "-" },
         { dt: 5, day: "Thu", event: "", do: "2" },
         { dt: 6, day: "Fri", event: "", do: "3" },
         { dt: 7, day: "Sat", event: "", do: "-" },
         { dt: 8, day: "Sun", event: "", do: "-" },
         { dt: 9, day: "Mon", event: "", do: "4" },
         { dt: 10, day: "Tue", event: "", do: "5" },
         { dt: 11, day: "Wed", event: "", do: "1" },
         { dt: 12, day: "Thu", event: "", do: "2" },
         { dt: 13, day: "Fri", event: "", do: "3" },
         { dt: 14, day: "Sat", event: "", do: "-" },
         { dt: 15, day: "Sun", event: "", do: "-" },
         { dt: 16, day: "Mon", event: "", do: "4" },
         { dt: 17, day: "Tue", event: "", do: "5" },
         { dt: 18, day: "Wed", event: "", do: "1" },
         { dt: 19, day: "Thu", event: "", do: "2" },
         { dt: 20, day: "Fri", event: "", do: "3" },
         { dt: 21, day: "Sat", event: "", do: "-" },
         { dt: 22, day: "Sun", event: "", do: "-" },
         { dt: 23, day: "Mon", event: "", do: "4" },
         { dt: 24, day: "Tue", event: "", do: "5" },
         { dt: 25, day: "Wed", event: "", do: "1" },
         { dt: 26, day: "Thu", event: "", do: "2" },
         { dt: 27, day: "Fri", event: "", do: "3" },
         { dt: 28, day: "Sat", event: "", do: "-" },
      ]
   },
   {
      month: "March 2026",
      days: [
         { dt: 1, day: "Sun", event: "", do: "-" },
         { dt: 2, day: "Mon", event: "", do: "4" },
         { dt: 3, day: "Tue", event: "", do: "5" },
         { dt: 4, day: "Wed", event: "", do: "1" },
         { dt: 5, day: "Thu", event: "", do: "2" },
         { dt: 6, day: "Fri", event: "", do: "3" },
         { dt: 7, day: "Sat", event: "", do: "-" },
         { dt: 8, day: "Sun", event: "", do: "-" },
         { dt: 9, day: "Mon", event: "", do: "4" },
         { dt: 10, day: "Tue", event: "", do: "5" },
         { dt: 11, day: "Wed", event: "", do: "1" },
         { dt: 12, day: "Thu", event: "", do: "2" },
         { dt: 13, day: "Fri", event: "", do: "3" },
         { dt: 14, day: "Sat", event: "", do: "-" },
         { dt: 15, day: "Sun", event: "", do: "-" },
         { dt: 16, day: "Mon", event: "", do: "4" },
         { dt: 17, day: "Tue", event: "", do: "5" },
         { dt: 18, day: "Wed", event: "", do: "1" },
         { dt: 19, day: "Thu", event: "Telugu New Year’s Day - Holiday", do: "-" },
         { dt: 20, day: "Fri", event: "", do: "2" },
         { dt: 21, day: "Sat", event: "Ramzan - Holiday", do: "-" },
         { dt: 22, day: "Sun", event: "", do: "-" },
         { dt: 23, day: "Mon", event: "", do: "3" },
         { dt: 24, day: "Tue", event: "", do: "4" },
         { dt: 25, day: "Wed", event: "", do: "5" },
         { dt: 26, day: "Thu", event: "", do: "1" },
         { dt: 27, day: "Fri", event: "", do: "2" },
         { dt: 28, day: "Sat", event: "", do: "-" },
         { dt: 29, day: "Sun", event: "", do: "-" },
         { dt: 30, day: "Mon", event: "", do: "3" },
         { dt: 31, day: "Tue", event: "", do: "4" },
      ]
   },
   {
      month: "April 2026",
      days: [
         { dt: 1, day: "Wed", event: "", do: "5" },
         { dt: 2, day: "Thu", event: "", do: "1" },
         { dt: 3, day: "Fri", event: "Good Friday - Holiday", do: "-" },
         { dt: 4, day: "Sat", event: "", do: "-" },
         { dt: 5, day: "Sun", event: "", do: "-" },
         { dt: 6, day: "Mon", event: "", do: "2" },
         { dt: 7, day: "Tue", event: "", do: "3" },
         { dt: 8, day: "Wed", event: "", do: "4" },
         { dt: 9, day: "Thu", event: "", do: "5" },
         { dt: 10, day: "Fri", event: "", do: "1" },
         { dt: 11, day: "Sat", event: "", do: "-" },
         { dt: 12, day: "Sun", event: "", do: "-" },
         { dt: 13, day: "Mon", event: "", do: "2" },
         { dt: 14, day: "Tue", event: "Tamil New Year / Ambedkar B'day - Holiday", do: "-" },
         { dt: 15, day: "Wed", event: "", do: "3" },
         { dt: 16, day: "Thu", event: "", do: "4" },
         { dt: 17, day: "Fri", event: "", do: "5" },
         { dt: 18, day: "Sat", event: "", do: "-" },
         { dt: 19, day: "Sun", event: "", do: "-" },
         { dt: 20, day: "Mon", event: "", do: "1" },
         { dt: 21, day: "Tue", event: "", do: "2" },
         { dt: 22, day: "Wed", event: "", do: "3" },
         { dt: 23, day: "Thu", event: "General Election - Holiday", do: "-" },
         { dt: 24, day: "Fri", event: "", do: "4" },
         { dt: 25, day: "Sat", event: "", do: "-" },
         { dt: 26, day: "Sun", event: "", do: "-" },
         { dt: 27, day: "Mon", event: "", do: "5" },
         { dt: 28, day: "Tue", event: "", do: "1" },
         { dt: 29, day: "Wed", event: "", do: "2" },
         { dt: 30, day: "Thu", event: "", do: "3" },
      ]
   },
   {
      month: "May 2026",
      days: [
         { dt: 1, day: "Fri", event: "May Day - Holiday", do: "-" },
         { dt: 2, day: "Sat", event: "", do: "-" },
         { dt: 3, day: "Sun", event: "", do: "-" },
         { dt: 4, day: "Mon", event: "", do: "4" },
         { dt: 5, day: "Tue", event: "", do: "5" },
         { dt: 6, day: "Wed", event: "Last Working Day", do: "1" },
         { dt: 7, day: "Thu", event: "", do: "2" },
         { dt: 8, day: "Fri", event: "", do: "3" },
         { dt: 9, day: "Sat", event: "", do: "-" },
         { dt: 10, day: "Sun", event: "", do: "-" },
         { dt: 11, day: "Mon", event: "", do: "4" },
         { dt: 12, day: "Tue", event: "", do: "5" },
         { dt: 13, day: "Wed", event: "", do: "1" },
         { dt: 14, day: "Thu", event: "", do: "2" },
         { dt: 15, day: "Fri", event: "", do: "3" },
         { dt: 16, day: "Sat", event: "", do: "-" },
         { dt: 17, day: "Sun", event: "", do: "-" },
         { dt: 18, day: "Mon", event: "", do: "4" },
         { dt: 19, day: "Tue", event: "", do: "5" },
         { dt: 20, day: "Wed", event: "", do: "1" },
         { dt: 21, day: "Thu", event: "", do: "2" },
         { dt: 22, day: "Fri", event: "", do: "3" },
         { dt: 23, day: "Sat", event: "", do: "-" },
         { dt: 24, day: "Sun", event: "", do: "-" },
         { dt: 25, day: "Mon", event: "", do: "4" },
         { dt: 26, day: "Tue", event: "Muharram - Holiday", do: "-" },
         { dt: 27, day: "Wed", event: "", do: "5" },
         { dt: 28, day: "Thu", event: "Bakrid - Holiday", do: "-" },
         { dt: 29, day: "Fri", event: "", do: "1" },
         { dt: 30, day: "Sat", event: "", do: "-" },
         { dt: 31, day: "Sun", event: "", do: "-" },
      ]
   },
   {
      month: "June 2026",
      days: [
         { dt: 1, day: "Mon", event: "", do: "2" },
         { dt: 2, day: "Tue", event: "", do: "3" },
         { dt: 3, day: "Wed", event: "", do: "4" },
         { dt: 4, day: "Thu", event: "", do: "5" },
         { dt: 5, day: "Fri", event: "", do: "1" },
         { dt: 6, day: "Sat", event: "", do: "-" },
         { dt: 7, day: "Sun", event: "", do: "-" },
         { dt: 8, day: "Mon", event: "", do: "2" },
         { dt: 9, day: "Tue", event: "", do: "3" },
         { dt: 10, day: "Wed", event: "", do: "4" },
         { dt: 11, day: "Thu", event: "", do: "5" },
         { dt: 12, day: "Fri", event: "", do: "1" },
      ]
   }
];

export function getDayOrderFromPlanner(date: Date = new Date()) {
   const monthLabel = date.toLocaleString('en-US', { month: 'long', year: 'numeric' });
   const dt = date.getDate();
   
   const monthData = PLANNER_DATA.find(p => p.month === monthLabel);
   if (!monthData) return 0;
   
   const dayData = monthData.days.find(d => d.dt === dt);
   if (!dayData || dayData.do === "-") return 0;
   
   return parseInt(dayData.do) || 0;
}
